### ISSUE TITLE
NextUnset() routine to find next available bit 

### ISSUE THREAD

**Issue by jainvipin** [willf/bitset#25]
I am using this lib to manage a set of resources; in order to do that I was looking for some routine like func `func (b *BitSet) NextUnSet(i uint) (uint, bool)` that could tell me the first unused bit; the implementation can be almost along the lines of NextSet() function. If there is a way to achieve this with what exists today, except for checking bitset.Test() in a loop.

If nothing exists, and you see a generic use of this funciton, I can submit a PR...

**Comment by willf** [comment]
I think it will require a new function. Feel free to submit a PR.
