### ISSUE TITLE
Feature request: Gob Encoder and decoder

### ISSUE THREAD

**Issue by kartiksura** [willf/bitset#27]
It will be nice to have a gob encoder decoder, so that we can send it across the wire.
I can provide the patch :) and have it ready

**Comment by willf** [comment]
@kartiksura Please provide a Pull Request, and I'll add it.

**Comment by willf** [comment]
@kartiksura ^^ bump

**Comment by willf** [comment]
@kartiksura ^^ bump. I'll reopen if you provide the patch.
