### ISSUE TITLE
Allow package to work with App Engine 'goapp' tool.

### ISSUE THREAD

**Issue by ThePiachu** [willf/bitset#28]
Google app Engine can't assamble `*.s` files, so any GAE app that uses this library won't be able to run tests for example, due to "no such tool 6a". Relevant discussion - https://github.com/btcsuite/fastsha256/pull/2 .

The fix for this issue is simple - it consists of adding one flag to all .s files:

```
// +build !appengine
```

**Comment by willf** [comment]
Do you want to add this, and create a pull request?

**Comment by ThePiachu** [comment]
Setting it up would probably take me more time than it would take you. The change affects one file: `popcnt_amd64.s` and it requires adding `// +build !appengine` at the start of the file. I can do the pull request if you want, but it would probably be faster for you to do it.

**Comment by willf** [comment]
Ok, lmk if you see issues.

-- 
Will Fitzgerald

On February 11, 2015 at 2:52:12 PM, ThePiachu (notifications@github.com) wrote:

Setting it up would probably take me more time than it would take you. The change affects one file: popcnt_amd64.s and it requires adding // +build !appengine at the start of the file. I can do the pull request if you want, but it would probably be faster for you to do it.
