### ISSUE TITLE
IsSuperSet and IsStrictSuperSet

### ISSUE THREAD

**Issue by chrisprobst** [willf/bitset#30]
What do you think about adding these two methods ?
I kinda miss these a lot when working with sets.

**Comment by chrisprobst** [comment]
An implementation could look like this:

func IsSuperSet(a, b *bitset.BitSet) bool {
	for i, e := b.NextSet(0); e; i, e = b.NextSet(i + 1) {
		if !a.Test(i) {
			return false
		}
	}
	return true
}

func IsStrictSuperSet(a, b *bitset.BitSet) bool {
	return a.Len() > b.Len() && IsSuperSet(a, b)
}

**Comment by willf** [comment]
I've added IsSuperSet and IsStrictSuperSet as methods on BitSet. Note that the 2nd function is actually wrong; it should return a.Count() > b.Count() && IsSuperSet(a, b). This is reflected in the code.

**Comment by chrisprobst** [comment]
I've just noticed, that the implementation of IsSuperSet is not the same, as I suggested, which introduces an error.

The current impl. is:
```
// IsSuperSet returns true if this is a superset of the other set
func (b *BitSet) IsSuperSet(other *BitSet) bool {
	for i, e := b.NextSet(0); e; i, e = b.NextSet(i + 1) {
		if !other.Test(i) {
			return false
		}
	}
	return true
}
```

IMHO it should be:
```
// IsSuperSet returns true if this is a superset of the other set
func (b *BitSet) IsSuperSet(other *BitSet) bool {
	for i, e := other.NextSet(0); e; i, e = other.NextSet(i + 1) {
		if !b.Test(i) {
			return false
		}
	}
	return true
}
```

The test didn't catch this situation, because both sets have the same bits set.

It introduced a nasty error in my codebase and I simply couldn't find it. After changing this, everything worked fine =).
