### ISSUE TITLE
Varint based serialization?

### ISSUE THREAD

**Issue by JustinAzoff** [willf/bitset#32]
Hi, I would like to add a more space efficient serialization method.  I'm playing around with storing the bitsets in something like leveldb. I don't need the length that WriteTo adds, and in my use cases using varint encoding would be much more space efficient (generally will only be keeping track of something like 24 or 288 bits, maybe 4x that as an extreme

```
package main

import (
    "bytes"
    "encoding/binary"
    "fmt"
    "github.com/willf/bitset"
)

func PutUVarint(v uint64) []byte {
    b := make([]byte, 10)
    written := binary.PutUvarint(b, uint64(v))
    return b[:written]
}

func main() {
    bs := bitset.New(8)
    bs.Set(1)
    bs.Set(3)
    bs.Set(5)
    bs.Set(288)
    //fmt.Printf("Bits: %s\n", bs.DumpAsBits())
    fmt.Printf("Len: %d\n", bs.Len())
    fmt.Printf("BinaryStorageSize: %d\n", bs.BinaryStorageSize())

    buffer := bytes.NewBuffer(make([]byte, 0, bs.BinaryStorageSize()))
    bs.WriteTo(buffer)
    fmt.Printf("Output buffer looks like %#v\n", buffer.Bytes())

    fmt.Printf("Varint looks like %#v\n", PutUVarint(1|3|5|288))
}
```

Outputs:

```
Len: 289
BinaryStorageSize: 48
Output buffer looks like []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0}
Varint looks like []byte{0xa7, 0x2}
```

(aside: leveldb compression seems to help quite a bit with this, but I'm hoping a smaller encoding is faster)

**Comment by lemire** [comment]
@JustinAzoff 

There are dedicated bitmap compression libraries in Go:

https://godoc.org/github.com/tgruben/roaring

http://zhen.org/blog/bitmap-compression-using-ewah-in-go/

It might be interesting to do some benchmarking.

**Comment by JustinAzoff** [comment]
@lemire 

Thanks for the links, very interesting stuff.

I realized my test above was slightly wrong, I should have used 2^288, not 288

I ran some more tests for just storing 1,3,5,23. (which minimally i believe is just 2|8|32|8388608)

varint: {0xaa, 0x80, 0x80, 0x4}
bitset: {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x0, 0x2a}
roaring: {0x3a, 0x30, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, 0x0, 0x10, 0x0, 0x0, 0x0, 0x1, 0x0, 0x3, 0x0, 0x5, 0x0, 0x17, 0x0}

I think the libraries/output formats are just not optimized for the case of trying to pack < 64 bits into the smallest output possible.

If I stick with leveldb I think using varint may be pointless anyway as snappy seems to do a good job at compressing all the 0x0's in the bitset output. I'd just be swapping one kind of compression for another.

If anyone cares, my use case here is mapping terms to documents(log files) in daily sharded leveldb databases.  In most environments there will only be 24 (60 minute) log files per day, a upper bound would be something like 288 (5 minute files) * 5 sources = 1440 daily document ids.

**Comment by JustinAzoff** [comment]
Oh hey! Forgot all about this issue I made, thanks for closing :-)

Yeah, this turned out to be a non-issue.  bitset+snappy in most conditions beat everything else I tried.. and I tried compressing msgpack encoded integer lists that were delta encoded.  I think I got it smaller at one point, but the performance was terrible.

bitset rocks!

**Comment by lemire** [comment]
Compression based on delta encoding should just smoke snappy (be at least an order of magnitude faster).

**Comment by JustinAzoff** [comment]
Ah, if you're interested, here was my size comparison test program:

https://github.com/JustinAzoff/flow-indexer/blob/feature/delta-msgpack/experiments/size_comparison.go

outputs

    test      :     bitset   bitset.s    msgpack  msgpack.s   msgpackd msgpackd.s msgpackd.z msgpackd.s/bitset.s
    just 0    :         16         12          2          4          2          4         14         33%
    just 1    :         16         12          2          4          2          4         14         33%
    just 13   :         16         12          2          4          2          4         14         33%
    just 23   :         16         13          2          4          2          4         14         30%
    just 600  :         88         20          4          6          4          6         16         30%
    just 6000 :        760         51          4          6          4          6         16         11%
    1,4,8,12  :         16         12          5          7          5          7         17         58%
    0-23      :         16         13         27         10         27         11         20         84%
    0-720     :        104         21        723         44        723         45         24        214%
    0-8640    :       1088         61       8643        413       8643        414         42        678%
    0,1024    :        144         26          5          7          5          7         17         26%
    rand      :        368         66         19         21         49         36         43         54%
    fib       :         88         46         18         20         16         18         28         39%
    fibmore   :       9392        532         50         52         46         48         60          9%

snappy compressed bitset does really well until the fibmore test which adds some really sparse values up to 75025.  Delta encoding made no difference for snappy(but gzip worked well).  bitset was just so much faster than everything when I did a full end to end test.

**Comment by lemire** [comment]
@JustinAzoff  Have you had a look at @zhenjl 's extensive experiments on integer compression in Go? He has a corresponding software library...

http://zhen.org/blog/benchmarking-integer-compression-in-go/
