### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by fansgit** [willf/bitset#40]
I've compared [willf/bitset](https://github.com/willf/bitset/) to [std::bitset](http://www.cplusplus.com/reference/bitset/bitset/) , and found that the `go version` has virtually performed  an order of magnitude slower than the `c++ counterpart`. 

Is `c++` generally still far superior to `go` for `CPU-bound` tasks?

**Comment by lemire** [comment]
Have you published your benchmarks? It would be very useful to have actual code with the actual numbers you are getting.

**Comment by fansgit** [comment]
I used [boost::dynamic_bitset] (http://www.boost.org/doc/libs/1_61_0/libs/dynamic_bitset/dynamic_bitset.html) instead and turned on `gcc -O3`, which actually only got 5 times more speedy than `go` below,

```go
package main

import (
        "fmt"
        "github.com/willf/bitset"
        "time"
)

const N uint = 100000

func main() {
        t := time.Now()
        var b, b2 bitset.BitSet
        for i := N; i > 0; i-- {
                b.Set(i)
                b.NextSet(0)
                b2.InPlaceUnion(&b)
        }
        fmt.Println(int64(time.Now().Sub(t) / time.Nanosecond))
}

```
```c++
#include <boost/dynamic_bitset.hpp>
#include <chrono>
#include <iostream>

#define N 100000

int main()
{
    boost::dynamic_bitset<> b(N + 1), b2(N + 1);
    auto t = std::chrono::system_clock::now();
    for (int i = N; i > 0; i --)
    {
        b[i] = 1;
        b.find_next(0);
        b2 |= b;
    }
    std::cout << (std::chrono::system_clock::now() - t).count() << std::endl;
}
```

**Comment by lemire** [comment]
I think that a 5x factor is to be expected when comparing Go to C.  
Speaking for myself, I am hoping that Go 1.7 makes it easier to understand performance issues.

**Comment by willf** [comment]
Thanks, all.

**Comment by josharian** [comment]
What version of Go were you using? Will you try again (if necessary) with the Go 1.7 beta? The new SSA backend for amd64 should help.

5x is too much. If there is still a significant slowdown, please file an issue at golang.org/issue/new and we'll take a look for 1.8.

Also, please use the standard testing benchmark setup when benchmarking Go code, or if you must roll your own, call runtime.GC before the critical section to make sure you're not also accidentally benchmarking garbage collection. (GC is a cost in Go, but if we're comparing numerical code, it's not the relevant factor.)

Thanks! And thanks to @lemire for pointing this out to me. C-level performance is not a goal, but 5x is too much.

**Comment by fansgit** [comment]
`go 1.7beta2`

The test framework chose to iterate 1000000 times and the benchmark reached to encouragingly half of the  c++ dear.
 
```go
package perf

import (
        . "github.com/willf/bitset"
        "testing"
)

func BenchmarkBitSet(tb *testing.B)  {
        var b, b2 BitSet
        for i, j, k := uint(tb.N), uint(tb.N-1), 0; k < tb.N; i, j, k = i-1, j-1, k+1 {
                b.Set(i)
                b2.Set(j)
                b.Union(&b2).NextSet(0)
        }
}
```

**Comment by lemire** [comment]
@josharian 

A simple straight C program can compute an in-place bitwise operation using 0.7 cycles per word... See https://github.com/lemire/cbitset/blob/master/benchmarks/benchmark.c (Underlying code here: https://github.com/lemire/cbitset/blob/master/src/bitset.c#L157-L166 See? No magic.)

When going from Go 1.5 to 1.7beta, using the program below, I go from 3 cycles per word to 2 cycles per word... Compared to C, this means going from 4.3 x slower to 2.9 x slower.

I am glad to see such progress.

It is important, however, to set people's expectation in the right light. Go is not a substitute for C or C++ as far as performance goes. (That's fine, because Go is  higher-level.)

```go
// file: run_test.go
package main

import (
        "testing"
)


// go test -bench BenchmarkIntersection -run -
func BenchmarkIntersectionBitset(b *testing.B) {
    b.StopTimer()
    wc := uint(1000)
    s1 :=  make([]uint64, wc, wc)
    s2 :=  make([]uint64, wc, wc)

    for i := uint(0); i < wc; i++ {
        s1[i] = uint64(i)
        s2[i] = uint64(i + 2)
    }
    b.StartTimer()
    for j := 0; j < b.N; j++ {
        for w:= uint(0); w < wc ; w++ {
          s1[w] &= s2[w]
        }
    }
}
```

**Comment by fansgit** [comment]
I also did one more fair comparison in `java 1.8`, and the outcome tied with `go 1.7`.

```java
import java.util.BitSet;

public class Main2 {
    static final int N = 1000000;
    public static void main(String[] args) {
        long t = System.nanoTime();
        BitSet b = new BitSet(N + 1);
        BitSet b2 = new BitSet(N + 1);
        for (int i = N, j = N - 1; j > 0; i --, j --)  {
            b.set(i);
            b2.set(j);
            BitSet b3 = (BitSet)b.clone();
            b3.or(b2);  
            b3.nextSetBit(0);
        }
        System.out.println(System.nanoTime() - t);
    }
}

```

**Comment by fansgit** [comment]
I reused the simple bitAnd testcase from @lemire, where any potential GC should take a detour.

```go
import (
        "fmt"
        "time"
)

const N uint = 100000000

func main() {
        s := make([]uint64, N)
        s2 := make([]uint64, N)
        for i := uint(0); i < N; i++ {
                s[i] = uint64(i)
                s2[i] = uint64(i + 2)
        }

        t := time.Now()
        for i := uint(0); i < N; i++ {
                s[i] &= s2[i]
        }
        fmt.Println(int64(time.Now().Sub(t) / time.Nanosecond))
}
```

The same test in `rust 1.9.0` hit 4x slower than `go 1.7 beta2` but managed on deuce if `rustc -O` turned on.

```rust
extern crate time;

use time::get_time;

const N: usize = 100_000_000;

fn main()
{
    let mut v = vec![0; N];
    let mut v2 = vec![0; N];
    for i in 0..N {
        v[i] = i as u64;
        v2[i] = (i + 2) as u64;
    }

    let t = get_time();
    for i in 0..N {
        v[i] &= v2[i]
    }
    let t2 = get_time();
    println!("{}", (t2.sec - t.sec) * 1_000_000_000 + (t2.nsec - t.nsec) as i64);
}
```

Finally, I've somehow felt that `java, go and rust` currently belong to the same league in terms of number crunching.
