### ISSUE TITLE
request for updating of license to Apache 

### ISSUE THREAD

**Issue by chandradeepak** [willf/bitset#49]

**Comment by lemire** [comment]
I'd be interested in the rationale behind this issue. In which cases is the current license an impediment?

**Comment by chandradeepak** [comment]
Yeah. All external dependency go through scans and they reject license if hey are not Apache or not .the current license statement is too generic and generally the reject them to keep out of trouble.

**Comment by lemire** [comment]
> "the current license statement is too generic"

What are the accepted licenses? Do you have a list?

**Comment by chandradeepak** [comment]
Apache would be perfect. MIT or bad is also ok

**Comment by chandradeepak** [comment]
Sorry BSD license

**Comment by lemire** [comment]
@willf  The current license is BSD, is it not?

**Comment by chandradeepak** [comment]
Not it doesn't say that in the license.txt

**Comment by lemire** [comment]
@chandradeepak  

The statement of the BSD license does not include the word "BSD". BSD is the name a Unix system. We refer to licenses that use the BSD template as being BSD licenses.

**Comment by chandradeepak** [comment]
It has the word Copyright (c) 2014 Will Fitzgerald n license.txt . that is why scans are failing

**Comment by lemire** [comment]
@chandradeepak 

To be precise, the first line is 

```
Copyright (c) 2014 Will Fitzgerald. All rights reserved.
```

Do the "scans" (whatever they are) allow you to use Go itself? Here is the corresponding first line in Go (taken from  https://github.com/golang/go/blob/master/LICENSE).

```
Copyright (c) 2009 The Go Authors. All rights reserved.
```

Notice how it is identical?

**Comment by chandradeepak** [comment]
i will try to validate this .  thanks for the input. i will close the issue .

**Comment by willf** [comment]
Thanks, all.
