### ISSUE TITLE
undefined: Bitset

### ISSUE THREAD

**Issue by Gujarats** [willf/bitset#51]
I have a problem when importing this package to my project. I have followed the following step to install the package :

-  go get github.com/willf/bitset <br>
and then in the code 
```
package database
import (
	"bitset"
         // other package
)

func GetActiveSeller(keyActiveSeller string) uint {
	var b BitSet
	b.Set(10).Set(11)
	if b.Test(1000) {
		b.Clear(1000)
	}
//some other code
}
```
But I still get undefined BitSet. also I tried to import the package using ` import "github.com/willf/bitset"`. and then `go get`.
But still the undefined. please help me on this ? Thank you

**Comment by lemire** [comment]
Try something like this:

```go

import (
	"github.com/willf/bitset"
)

var b bitset.BitSet
```

**Comment by Gujarats** [comment]
@lemire nope it is still doesn't work. is it just me or are you having the same problem?

**Comment by lemire** [comment]
Many, many people depend on willf/bitset. It is pretty standard.

**Comment by willf** [comment]
The following steps on a clean machine worked for me:

```bash
~$ go version
go version go1.7.3 linux/amd64
~$ export GOPATH=/home/willf/go
~$ mkdir -p $GOPATH
~$ go get github.com/willf/bitset
~$ cat b.go
package main
import (
	"github.com/willf/bitset"
        "fmt"
)

func main() {
  var b bitset.BitSet
  b.Set(10)
  fmt.Println("Did a bit of work.")
}

$ go run b.go
Did a bit of work.
```
