### ISSUE TITLE
BUG: unexpected results in arm64 and x86 for TEstNewPanic

### ISSUE THREAD

**Issue by mckaygerhard** [willf/bitset#56]
when running test on arm 64bit i got and error:
https://github.com/willf/bitset/blob/1a37ad96e8c1a11b20900a232874843b5174221f/bitset_test.go#L981
i'm reading the Cap returns the total possible capacity, or number of bits , but reading the code of the test, i have not so clear if the xpected number are 0 or something!, in arm 64bits and i318 32bits got:

```
=== RUN   TestNewPanic
--- FAIL: TestNewPanic (0.55s)
	bitset_test.go:983: Unexpected value:  4294967295
```
seems the test got a 0 value, but documentation does not explainme so much

i need this to clear package and run in embebed devices with linux

the sources said:

```
// Cap returns the total possible capacity, or number of bits
func Cap() uint {
	return ^uint(0)
}
```

the test expected zero? previous test in https://github.com/willf/bitset/blob/1a37ad96e8c1a11b20900a232874843b5174221f/bitset_test.go#L963 proves and works.. but later the https://github.com/willf/bitset/blob/1a37ad96e8c1a11b20900a232874843b5174221f/bitset_test.go#L980 faild! i cant understand and as we can see its not related to 32 bits, due happened in arm 64

**Comment by lemire** [comment]
I'm not sure it is a bug.

However, the test might be bogus. It seems to try to allocate a super large bitset and it expects it to fail. If it does not fail, then it fails the test. 

At a minimum, the test should be documented.

For the record, I cannot verify the issue an aarch64 processor:

```
$ uname -a
Linux Softiron 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) aarch64 aarch64 aarch64 GNU/Linux
$ go version
go version go1.6.1 linux/arm64
$ go test
{0,1,2,3,4,5,6,7,8,9}
PASS
ok  	github.com/willf/bitset	0.102s
```

@willf  I can give you access to my aarch64 machine.

**Comment by QuLogic** [comment]
This test seems to fail on [i686](https://koji.fedoraproject.org/koji/taskinfo?taskID=29010428) and [armv7hl](https://koji.fedoraproject.org/koji/taskinfo?taskID=29010430) for me (both these systems are 32-bit.)

**Comment by lemire** [comment]
I removed the nonsensical test. The reason it fails on 32-bit systems is that for the test to pass, there has to be a panic (out of memory). This is not a very good test. If one wants to test out-of-memory conditions, it should not be done in such a manner.
