### ISSUE TITLE
integer limit

### ISSUE THREAD

**Issue by dongweigogo** [willf/bitset#57]
Since the bitset accepts uint, I think the upper limit of integers should be 2^64-1=18446744073709551615.
However, for an integer that is much smaller than that value (i.e. 123456789012345), my program panics.

panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
github.com/willf/bitset.(*BitSet).extendSetMaybe(0xc4200980a0, 0xbf980761e9d1fc7)

Is there anything I misunderstand in using this package?

**Comment by dongweigogo** [comment]
@lemire The server RAM is about 100G, I'm not sure if it's enough.

**Comment by lemire** [comment]
Well I suppose you need about 15 TB of RAM.

**Comment by dongweigogo** [comment]
you mean the byte count of 123456789012345 bits? I don't know how the bitset is implemented.

**Comment by lemire** [comment]
You divide the number of bits by eight and it gives you the number of bytes.

If you have lots of bits, you might prefer compressed bitsets, see http://roaringbitmap.org (there is a Go implementation).

**Comment by lemire** [comment]
I am going to close this, there should be no expectation that any data structure has infinite storage. I have added some documentation in the README.
