### ISSUE TITLE
Compacting the BitSet

### ISSUE THREAD

**Issue by maciej** [willf/bitset#64]
Currently there is no way to compact the `BitSet`. The _README.md_ states:
> BitSets are never shrunk

I suggest adding a _Compact_ method
```go
func (b *BitSet) Compact() {}
```
which would compact the BitSet in place.

I'm willing to issue a PR as long as it gets reviewed and has a chance of getting accepted.

**Comment by lemire** [comment]
I'm willing to review it, and I am inviting the PR.

**Comment by maciej** [comment]
@lemire you can always be counted on when it comes to swift responses and good reviews!

**Comment by cristaloleg** [comment]
Any progress on this? 😺
