### ISSUE TITLE
Faster performance by allocating more space in extendSetMaybe()

### ISSUE THREAD

**Issue by zhenjl** [willf/bitset#7]
https://github.com/willf/bitset/blob/master/bitset.go#L98

Right now you are allocating up to the biggest bit. However, this could really be slow a lot of bits are set continuously. For example, [this test](https://github.com/zhenjl/bitmap/blob/master/bitset/bitset_test.go#L63) ran 64 seconds to run.

--- PASS: TestSet2 (64.51 seconds)

If you allocate more space (nsize_2), it will speed up performance dramatically. So with nsize_2, and fixing the other length check issue in Intersection() and Not(), the test is now much faster.

--- PASS: TestSet2 (0.28 seconds)

Only problem is now the bit array might be much more than you need. In which case a Trim() function can be implemented to trim it back when needed.

**Comment by willf** [comment]
I think we addressed this.
