### ISSUE TITLE
Tag a new v1.1.11 patch release for go mod

### ISSUE THREAD

**Issue by thaJeztah** [willf/bitset#83]
The opencontainers/go-selinux package, as used in runc and other container runtimes recently added this package as a dependency. While working on the implementation, the contributor noticed a bug in the bitset package that was fixed on master, but not yet released https://github.com/opencontainers/selinux/pull/103#issuecomment-651861843

From the diff, it looks like various (minor) fixes went into the master branch since the last release; https://github.com/willf/bitset/compare/v1.1.10...master

With go modules, it's best practice to use tagged versions of dependencies, so opening this ticket to inform if it's possible to tag a `v1.1.11` patch release

**Comment by thaJeztah** [comment]
@willf PTAL

/cc @rhatdan @kolyshkin

**Comment by lemire** [comment]
tagged

**Comment by thaJeztah** [comment]
Thank you so much!

**Comment by willf** [comment]
Thanks @lemire !
